### PR TITLE
use provider to create MapboxNavigation instance

### LINKED ISSUE #93: Crash in ShowManeuversActivity
```2022-06-09 15:00:04.146 12534-12534/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 12534
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.navigation.examples/com.mapbox.navigation.examples.maneuvers.ShowManeuversActivity}: java.lang.IllegalStateException: A different MapboxNavigation instance already exists.
    Make sure to destroy it with #onDestroy before creating a new one.
    Also see MapboxNavigationProvider for instance management assistance.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalStateException: A different MapboxNavigation instance already exists.
    Make sure to destroy it with #onDestroy before creating a new one.
    Also see MapboxNavigationProvider for instance management assistance.
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:383)
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:216)
        at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
        at com.mapbox.navigation.examples.maneuvers.ShowManeuversActivity.onCreate(ShowManeuversActivity.kt:273)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        	... 12 more
```
        	
Steps to reproduce:
1. Run app;
2. Go to "Render Current Location On Map screen";
3. Go back;
4. Go to "Render Maneuver Instructions For a Route" screen.

The same issue for other examples was fixed here: https://github.com/mapbox/mapbox-navigation-android/pull/4917/files

### PR DESCRIPTION
**Pull request by dzinad**
Fixes #93.

### CODE REVIEW

**Comment by dzinad** [comment]
I didn't find any unit tests or changelog to be updated for these changes.

**Review by RingerJK — APPROVED** [review]

**Comment by RingerJK** [comment]
> I didn't find any unit tests or changelog to be updated for these changes.

because we don't have unit tests here 😄 Most cases are covered in the original repo and 1TAP. We can add tests for repo-specific business logic, do you see any?

**Comment by dzinad** [comment]
> We can add tests for repo-specific business logic, do you see any?

Which repo? This one or the sdk? Adding unit tests for the examples seems kinda weird.

File: app/src/main/java/com/mapbox/navigation/examples/location/ShowCurrentLocationActivity.kt [hunk 1]
```diff
@@ -137,7 +137,7 @@ class ShowCurrentLocationActivity : AppCompatActivity() {
 
     @SuppressLint("MissingPermission")
     private fun initNavigation() {
-        mapboxNavigation = MapboxNavigation(
+        mapboxNavigation = MapboxNavigationProvider.create(
```
Comment (abhishek1508) [inline app/src/main/java/com/mapbox/navigation/examples/location/ShowCurrentLocationActivity.kt:140]: Instead of `MapboxNavigationProvider` let's change this to use `MapboxNavigationApp.setUp()`. Going forward, we are going to officially use `MapboxNavigationApp` more and more and this might become our preferred way to instantiate `mapboxNavigation` starting `v3.0`. `MapboxNavigationProvider` is something we might remove

cc @RingerJK @Zayankovsky @dzinad

Comment (abhishek1508) [reply app/src/main/java/com/mapbox/navigation/examples/location/ShowCurrentLocationActivity.kt:140]: Wait but `MapboxNavigationApp` is still `Experimental`. Let's use `MapboxNavigationProvider` for now and I will cut a ticket to use `MapboxNavigationApp` once the `Experimental` annotation is removed. Sorry for the confusion.

Comment (dzinad) [reply app/src/main/java/com/mapbox/navigation/examples/location/ShowCurrentLocationActivity.kt:140]: In public docs the provider is used: https://docs.mapbox.com/android/navigation/guides/get-started/initialization/
